xport const SITE = {
  website: "https://YourUrl.com",
  author: "YourName",
  profile: "YourProfileUrl",
  desc: "YourDescription.",
  title: "YourTitle",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  lang: "zh",
  timezone: "Asia/Shanghai",
} as const;
